### ISSUE TITLE
slow performance while loading files

### ISSUE THREAD

**Issue by avstri** [VPKSoft/ScintillaDiff#1]
try >1000 line file
if you change DiffTextsSideBySide to add all the lines to stringbuilder then call AppendRow once - then the performance is fast.

**Comment by VPKSoft** [comment]
I'll look into this - thanks 👍

**Comment by VPKSoft** [comment]
Thanks for bringing this to the next decade! Fix at commit 5249714, also released a NuGet package. 🥳

**Comment by VPKSoft** [comment]
Fixed
