### ISSUE TITLE
Bug in Character Comparison

### ISSUE THREAD

**Issue by Rabbit800** [VPKSoft/ScintillaDiff#13]
Hi,
I believe there is a bug when CharacterComparison property is set to true, and CharacterComparisonMarkAddRemove set to false, for sidebyside comparison. The scintilla control may add virtual blank lines to map to the extra lines in the other file, and then the line offsets will no longer match the correct lines in editor. It will highlight lines that are identical.
You can replicate while comparing some xml files, which have one element per line.

**Comment by VPKSoft** [comment]
Could you paste a screenshot please - it would give somewhat nicer understanding of the bug in question? 🤔
