### ISSUE TITLE
Highlighting bug

### ISSUE THREAD

**Issue by Rabbit800** [VPKSoft/ScintillaDiff#14]
The colors of highlighed changes interfere with the color for text selection. Believe the text selection should be drawn on top.
If you try to use Find in the control, you can't see the selected text.
Second issue is that, although colors have an Alpha (transparency) component, the alpha parameter is not set for the highlight indicators.
I made small changes in the method that passes the highlighted ranges and applies the alpha component from the color to the range and it works. The method even had two alpha arguments, but they were not used.
Using alpha allows us to see the color selected text.
Suggest to consider making this change, to support alpha component in the colors for highlighted changes.

**Comment by VPKSoft** [comment]
Thanks, of course if you already invented a fix you could share the code or make a PR? 🙂

**Comment by VPKSoft** [comment]
Closing due inactivity.
