### ISSUE TITLE
View vs Edit

### ISSUE THREAD

**Issue by Rabbit800** [VPKSoft/ScintillaDiff#16]
Opening files for comparison will map empty lines to lines in the other file which have no match, in order to align the texts.
But I found that it will save the file with the empty lines included, if I get the text from the control (i.e. from left or right scintilla control).

Is the control supposed to be used only for viewing differences?
Is there a way to find which lines are virtual, to exclude them during save operation?

Other editors show those lines with gray background and will convert such a line, when edited, into a real line. On save, the gray lines are excluded.

**Comment by VPKSoft** [comment]
The control is for difference viewing only.
