### ISSUE TITLE
Empty string

### ISSUE THREAD

**Issue by Aghlara** [VPKSoft/ScintillaDiff#32]
Hi,

I want to compare the content of a file with an empty string, which technically means the content has been deleted entirely.

Meaning either of the `original` or `changed` below might be an empty string.
![image](https://user-images.githubusercontent.com/5187409/140656878-f5463bea-9389-4d7e-a889-f8141a3d90e9.png)

But because in the source the Diff happens when each side is not `string.Empty` it prevents it as below:
![image](https://user-images.githubusercontent.com/5187409/140656965-0159ac76-957d-421d-ac2c-fcaf19d5dcd0.png)

At the moment I have to add a space which as you can see is not correct:
![image](https://user-images.githubusercontent.com/5187409/140657029-c98e29d5-c1b2-400c-97e4-d691b49d7ca5.png)

How do we do this with your control?

**Comment by VPKSoft** [comment]
Does it work if you change the condition in the source code? If it does, the condition can be changed. You can create a PR if you wish or wait some time for me to check the code and see if the empty text works.

**Comment by VPKSoft** [comment]
The control now allows the other text to be empty as of version 1.1.2.
