### ISSUE TITLE
Compatibility with Diffplex 1.6.1

### ISSUE THREAD

**Issue by GalawynRM** [VPKSoft/ScintillaDiff#4]
Could be possible to update the nuget package to accept compability with Diffplex 1.6.1
I tried the from the source and compile and works.

I can't PR it, because I needed to change the targeting framework to 4.7.2

**Comment by VPKSoft** [comment]
Hi, I'll do that tomorrow, thanks.

**Comment by VPKSoft** [comment]
Hi, the NuGet is now released with the dependency update and few improvements due pull requests: https://www.nuget.org/packages/ScintillaDiff/1.0.0.5

**Comment by GalawynRM** [comment]
Thank you so much (I would do the PR but to do that I need to restart
computer and we don’t trust to restart them, we are working from remote). I
think you’re Finnish. My wife is Finnish.
