### ISSUE TITLE
Character based comparison

### ISSUE THREAD

**Issue by goroggy** [VPKSoft/ScintillaDiff#7]
Hi, his is a wonder control. 
However, I need character differences, how to do that?
Thanks.

**Comment by VPKSoft** [comment]
Hi, this seems to be matching word boundaries (the [DiffPlex](https://github.com/mmanela/diffplex) library) by default:
![image](https://user-images.githubusercontent.com/40712699/96208699-c922f100-0f76-11eb-8fc5-e7516e2ee3a3.png)
I assume you mean the side-by-side model which is created by the `SideBySideDiffBuilder` class.


I'll have to look into character diff once I have the time, maybe in the coming weekend...

**Comment by goroggy** [comment]
Thanks, that would be fine. Yes, I mean the sideBySide model.

**Comment by goroggy** [comment]
Diff has CreateCharacterDiffs but SideBySideDiffBuilder seems not to invoke it (you cannot pass a characterChunker).
I modified SideBySideDiffBuilder so that it takes CharacterChunker.Instance in place of WordChunker.Instance and it works: 
![image](https://user-images.githubusercontent.com/52278176/96225643-ae11aa80-0f91-11eb-9567-8a5c883a2dc9.png)

However I don't want to mess the code so please it would be nice if you could implement it. 

Btw the Difflpex PR 50 code examples say SideBySideBuilder instead of SideBySideDiffBuilder.

**Comment by VPKSoft** [comment]
Hi, The NuGet for the character based diff/comparison is now added to the [package](https://github.com/VPKSoft/ScintillaDiff/packages/453478), please let me know if there are any bugs 🤔
*New properties:*
![image](https://user-images.githubusercontent.com/40712699/96362995-1a2f1280-113a-11eb-9084-52d077bcae67.png)
*With the `CharacterComparison` property set:*
![image](https://user-images.githubusercontent.com/40712699/96363010-3cc12b80-113a-11eb-865f-efd7480d3db7.png)
*With both the `CharacterComparison` and the `CharacterComparisonMarkAddRemove` properties set:*
![image](https://user-images.githubusercontent.com/40712699/96363029-637f6200-113a-11eb-8666-60d448f05f0c.png)

TODO::Different project for the *unofficial.ScintillaNET* package.

**Comment by goroggy** [comment]
Thanks, Petteri, this is what I call fast service. Will be back with experience.

**Comment by goroggy** [comment]
Sorry, I have this error when the number of lines are not the same (and in my case it happens often)
Specified argument was out of the range of valid values.
Parameter name: startIndex
   at System.String.Insert(Int32 startIndex, String value)
   at ScintillaDiff.ScintillaDiffControl.SpanLeftRightChars(DiffResult diffResult, Int32 line, String oldLine, String newLine, List`1& charChangedList)
   at ScintillaDiff.ScintillaDiffControl.DiffTextsSideBySide()
   at ScintillaDiff.ScintillaDiffControl.set_TextRight(String value)

**Comment by VPKSoft** [comment]
Alright, need to look for a fix for that... perhaps too little test material was used 🙄

**Comment by VPKSoft** [comment]
Hi, the issue should be fixed now. Removing one `+1` should do the job 😅

> Fixed string.Insert error in case the CharacterComparisonMarkAddRemove property was set to true and a zero-length line occurred within the text.

**Comment by goroggy** [comment]
Thanks, the error disappeared. I think I will let the user choose between word based and character based comparisons. When the lines themselves do not much, character-based looks rather weird.
